### ISSUE TITLE
Add tquic to the 'quic-interop-runner' ?

### ISSUE THREAD

**Issue by cameronelliott** [Tencent/tquic#132]
I am just curious if you plan to add tquic to the `https://github.com/quic-interop/quic-interop-runner`

as described here: https://github.com/quic-interop/quic-interop-runner/blob/master/README.md#building-a-quic-endpoint

I see you have written an interop Dockerfile, etc.  - https://github.com/Tencent/tquic/tree/develop/interop

Thanks for creating tquic

**Comment by iyangsj** [comment]
Thanks for you attention. TQUIC is planed to join the quic interop matrix after the release of v0.6.0

**Comment by iyangsj** [comment]
We plan to add TQUIC to the `quic-interop-runner` after the release of v0.6.0.
