### ISSUE TITLE
Build relase/v0.5.0：`error: failed to select a version for the requirement `tquic = "^0.4.0"``

### ISSUE THREAD

**Issue by nixwl** [Tencent/tquic#136]
**Describe the bug**
 Linux(Ubuntu) 下 relase/v0.5.0 安装时出现的问题：`error: failed to select a version for the requirement `tquic = "^0.4.0"``

**To Reproduce**
将` ./tquic-0.5.0/tools/Cargo.toml `中的 
`tquic = { path = "..", version = "0.4.0"}`  为  `tquic = { path = "..", version = "0.5.0"}`

**Expected behavior**
修改完可以 build 了

**Comment by iyangsj** [comment]
感谢反馈，v0.6.0会解决类似问题

**Comment by iyangsj** [comment]
目前已经可以使用 v0.6.0

```
git clone -b v0.6.0 https://github.com/Tencent/tquic.git --recursive
cd tquic
cargo build --all
```
