### ISSUE TITLE
Unable to run the example code for the C API

### ISSUE THREAD

**Issue by Vaibtan** [Tencent/tquic#310]
I was trying out the example given in [https://github.com/tquic-group/tquic-example-c/tree/main](url). After makefile compilation, I was getting this memory leak error when running the simple_client executable [https://github.com/tquic-group/tquic-example-c/blob/main/simple_client.c](url) . How should I resolve this? 
![img](https://github.com/Tencent/tquic/assets/93938070/95c87582-36a6-4502-a05d-2a66d0188633)

**Comment by iyangsj** [comment]
@xiaofei0800
