### ISSUE TITLE
Deferring idle timeout

### ISSUE THREAD

**Issue by iyangsj** [Tencent/tquic#56]
Reference
* https://datatracker.ietf.org/doc/html/rfc9000#name-deferring-idle-timeout
* https://datatracker.ietf.org/doc/html/rfc9308#name-connection-termination

**Comment by stopandjoin** [comment]
这是计划添加quic内部的保活机制吗？  不知道连接迁移能不能也放在这个 v1.0.0 的milestone中 ^_^

**Comment by iyangsj** [comment]
连接迁移在v1.0.0版本的计划中
